#
# Makefile for the Essential specific device drivers.
#
subdir-ccflags-y := -Os
obj-$(CONFIG_SIDECAR) += sidecar.o
obj-$(CONFIG_ESSENTIAL_APR) += essential_apr.o
obj-$(CONFIG_ESSENTIAL_SENSOR) += essential_sensor_tof.o
obj-$(CONFIG_ESSENTIAL_MFR) += essential_mfr.o
subdir-ccflags-y += -Os